### ISSUE TITLE
sof-ctl and sof-probes missing for 1.9

### ISSUE THREAD

**Issue by kkga** [thesofproject/sof-bin#60] opened 2021-10-04 16:10 UTC
Trying to update the package for Void Linux and noticed that these tools are not provided for the latest release.

Just wanted to confirm whether it's intended, thanks.

**Comment by marc-hb** [comment] 2021-10-04 19:14
Very good question. The situation has been "fluctuating" with respect to these, sorry.

First of all, I think it's a generally bad idea to release Linux user space binaries when the entire source code is available because it tends to run in compatibility issues like `__stack_chk_fail symbol not found`. Even when no such compatibility issue happens, Linux distributions always recompile when they can for questions of performance, security (https://reproducible-builds.org/) and long story short _control_.

Now back to SOF, what happened is this: while redesigning, reimplementing and automating the entire packaging and release process from scratch to fix issues #25, #46 and others in time for v1.7, `sof-ctl` and `sof-probes` fell at the bottom of my priority list, apologies. Unlike the `sof-logger`, I consider these other two to be fairly "advanced" development tools so relying on developers to compile them did not seem like a big ask:
```
git clone https://github.com/thesofproject/sof
./scripts/build-tools.sh -h # and done?
```
Now you will ask: why are these binaries in v1.7 and v1.8? Because I _manually_ added them then  to the final release candidates (bd3a20e4745b) but later forgot I did and then wrongly assumed no one cared :-(

While fixing the very last issues like documentation (#61) and cleanups (#62) I ironically found the opportunity to finally implement the _automation_ to have them built and installed by default and I just submitted today a  cherry-pick that will indirectly add them to the v1.9.1 binaries: https://github.com/thesofproject/sof/pull/4840

Now that you know everything, I'm curious about your specific use case(s)?

cc: @perexg, @mrhpearson, @lgirdwood , @plbossart , @dbaluta

**Comment by plbossart** [comment] 2021-10-04 19:17
sof-ctl is a requirement for sof-test, just like sof-logger, so having a means to distribute it without having to re-compile would be a good thing.

**Comment by marc-hb** [comment] 2021-10-04 21:01
Right now `sof-ctl` seems required by only two sof-test: `test-case/check-keyword-detection.sh` and `test-case/check-audio-equalizer.sh`

**Comment by marc-hb** [comment] 2021-11-19 18:09
https://github.com/thesofproject/sof-bin/tree/main/v1.9.x/tools-v1.9.2 has `sof-ctl` and `sof-probes`. Unless there is some objection I will close this.

**Closed** 2021-11-24 18:23 UTC
